---
name: Pipeline Django

on:
  push:
    branches:
      - main

jobs:
  djangoapp:
    timeout-minutes: 15
    name: 'Djangoapp'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1